version: "3.9"
services:
  proxy:
    build: ./proxy
    ports:
      - "80:80"
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf
  web:
    build: ./web
    ports:
      - "3000"
    volumes:
      - ./web/source:/source
      - ./web/default.conf:/etc/nginx/conf.d/default.conf
